# Generated by Django 4.1.1 on 2022-10-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blof', '0002_alter_blog_options_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
